name: Quality Gate

on:
  push:
    branches:
      - alpha-release
    paths:
      - 'site/astro/**'
      - 'site/.github/workflows/**'
  pull_request:
    paths:
      - 'site/astro/**'
      - 'site/.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: site/astro/package-lock.json

      - name: Install dependencies
        working-directory: site/astro
        run: npm ci

      - name: Lint
        working-directory: site/astro
        run: npm run lint

      - name: Type check
        working-directory: site/astro
        run: npm run check

      - name: Unit tests
        working-directory: site/astro
        run: npm run test -- --run

      - name: Audit dependencies
        working-directory: site/astro
        run: npm audit --omit=dev --audit-level=moderate
